nome= str(input('Digite seu nome completo')).strip()
print('Analisando seu nome...')
print('Seu nome maiúsculo é {}'.format(nome.upper()))
print('Seu nome minusculo é {}'.format(nome.lower()))
print('Seu nome tem {} letras'.format(len(nome)-nome.count('nome')))
print('Seu primeiro nome tem {} letras'.format(nome.find('nome')))